### ISSUE TITLE
tiling option

### ISSUE THREAD

**Issue by dobkeratops** [teaearlgraycold/binimage#1]
would you consider the ability to show data in a grid of tiles, e.g.
treat the file as a 4d array , to be tiled into a 2d image; to just show 2D, pass 1 for the later sizes;
(e.g. if you had a sequential set of 64 16x16bit images, you could ask to show it as 16x16x 8x8, placing them in a square grid, showing as a 128x128 pixel image, rather than 16x1024)

(note the popularity of 4d arrays in neural nets)

the other arrangement that might be interesting is the [morton order curve](https://en.wikipedia.org/wiki/Z-order_curve)

**Comment by danthedaniel** [comment]
The morton order curve would require that the output image is of some size `2^n, 2^n`, right?

**Edit:**

Since you made reference to ANNs, would something like binimage actually be useful for them?

**Comment by dobkeratops** [comment]
> would something like binimage actually be useful for them?

i don't know, but it's just a thought that sprang to mind when messing around with debug.. imagine visualising channels by being able to just dump the memory to this utility

the real motivation was thinking what would happen with your 8pixel wide example.. it would be neat to coil this up into a squarer region, but maybe there's a simpler way to do that.

maybe it's too much.. is this a simple memory visualiser tool, or a retro game graphics extractor :) (feature-creep..)

> The morton order curve would require that the output image is of some size 2^n, 2^n, right?

it would indeed. I suppose you could pad the image out. it's just another idea for mapping something linear

**Comment by danthedaniel** [comment]
Maybe I could start by making binimage a library with a default driver implementation. That way there could be a rust interface and a CLI interface.

**Comment by dobkeratops** [comment]
a graphical analogy of a "debug-print" library , perhaps (graphical visualisation of internal states.. arrays, memory allocator,..)

**Comment by danthedaniel** [comment]
Would be useful when combined with a visual diff-ing function.
