### ISSUE TITLE
[FIXED] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [teaearlgraycold/binimage#4]
Dear Daniel,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by danthedaniel** [comment]
Should be easy enough, sure.

If you want to run this ASAP you can try using the Windows Subsystem for Linux if you're on Windows 10. Then you can run the provided linux binary natively.

**Comment by danthedaniel** [comment]
Finally remembered this while I was at a windows machine.

You can find a 64bit binary in the 0.2.0 release files:

https://github.com/teaearlgraycold/binimage/releases/tag/0.2.0

**Comment by sergeevabc** [comment]
@teaearlgraycold, it works as expected, thank you.
In case you’d like to evolve this project, consider adding output to pipe (e.g. with ```-``` switch of something).
